config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :products do
    post :import, on: :collection
 end
  root to: 'products#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
  
  def self.to_csv(options = {})
   CSV.generate(options) do |csv|
   csv << column_names
   all.each do |product|
      csv << product.attributes.values_at(*column_names)
    end
  end
end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

 def index
    @products =  Product.order(:order_no)
    respond_to do |format|
    format.html
    format.csv { send_data @products.to_csv, filename: "Master-CSV-#{Date.today}.csv" }
    # format.xls #{ send_data @products.to_csv(col_sep: "\t"), filename: "Master-CSV-#{Date.today}.xls" }
    end
  end

  def import
    file = params[:file]
      spreadsheet = Roo::Spreadsheet.open(file)

      header = spreadsheet.row(1)

      (2..spreadsheet.last_row).map do |i|
         next unless spreadsheet.row(i)[0]
         row = Hash[[header, spreadsheet.row(i)].transpose]
         row.default = ""

      b = row["Bank Name"]
      c = row["Payment Type"]
      d = row["MPS Amount"]
      e = row["Sale Tax Form Acknowledgement No."]    
      f = row["Invoice Zone"]
      g = row["Client"]
      h = row["Waybill"]
      i = row["invoice code"]
      j = row["product mrp"]
      k = row["sale discount"]
      l = row["price"]
      m = row["tax"]
      n = row["gross amount"]
      o = row["payment status"]
      q = row["customer email"]
      r = row["transaction date"]

      if row.key?("coupon_code")
        s = row["coupon_code"]
   end

   if row.key?("coupon value")
       s = row["coupon value"]
    end

    if row.key?("Type")
      t = row["Type"]
    end
    if row.key?("payment type")
      t = row["payment type"]
    end



       if row.key?("Amount")
       u = row["Amount"]
   end
   if row.key?("amount payable")
    u = row["amount payable"]
   end

     
      if row.key?("order code")
        a = row["order code"]  
    end
      if row.key?("Order #")
        a = row["Order #"]
    end
      if row.key?("Transaction ID")
        a = row["Transaction ID"]
      end

         import = Product.where(order_no: a , price: l , product_mrp: j , tax: m , sale_discount: k  , 
          gross_amount: n , amount_payable: u , bank_name: b , e_payment_type:  c , transaction_date: r , Sale_tax_form_acknowledgement_no: e , mps_amount: d)
        
        if import.exists?
           import.update(amount_payable: u)

        else
             y = Product.new(order_no: a , way_bill: h , invoice_code: i , client: g ,
           customer_email: q , invoice_zone: f , price: l , product_mrp: j , tax: m , sale_discount: k ,
            coupon_value: s , gross_amount: n ,  amount_payable: u , e_payment_type: c , payment_status: o ,  bank_name: b , payment_type: t , transaction_date: r ,
              Sale_tax_form_acknowledgement_no: e , mps_amount: d)
          
            y.save
           
        end

      end
      redirect_to root_url, notice: "Imported Successfully" and return
  end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StoreTest</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="container">
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, id: "flash_#{name}" %>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/products/index.html.erb
<h1 style ="position: relative; padding-left: 435px;">Payment Details</h1>

<h2>Import Products</h2>

<p>
  <strong>Download  || Output:</strong>
  <%= link_to "CSV", products_path(format: "csv") %> |
</p>

<%= form_tag import_products_path, multipart: true do %>
  <%= file_field_tag :file %>
  <%= submit_tag "Import" %>
<% end %>

<h4> 
	NOTICE: Since deploying it in cloud as a web all these conditions are to be taken care
	<br>
	<ul>
		<li>Mostly Order_feed have sufficient details except bank_name, customer-email, client name and E-payment type so, try to use this sheet alone, in rare case you upload prepaid remitance, last_mile & cod_sheet</li>
		<br>
<li>
As its a free hosting site, Please Upload max of 250 records per import.
else the server will be timed out.
</li>
<br>
<li>Assumption: sheets have `order code` one has `Order #` and `Transaction ID`.Here these 3 attributes have same length. Even though `Transaction ID` is different from other two in real time , Here, for making relation between each sheet I am considering them as same attribute with different header. </li>
<br>
<li>While uploading a sheet have check whether your sheet has `order code` or `Order #` or `Transaction ID` . Else it will through error.</li>
<br>
<li>DB can store only 10,000 records so please be aware of it</li>
<br>
<li>Due to unavailability of `ruby gem` for reading all formats, Here you can only upload .xlsx (the latest format of excel in MS) so, please convert your file and import, else it will through error. </li>
<br>
<li>Before Downloading the CSV/xls please feed the DB by uploading the input sheet. Initially the DB has no records.</li>
<br>
</h4>